---
- name: Configure DHCP server for router
  hosts: router
  become: yes
  
  tasks:
    - name: Gather distribution facts
      ansible.builtin.setup:
        gather_subset:
          - distribution
      tags: always
      
    - name: Install ISC DHCP Server (Trixie)
      ansible.builtin.command: apt-get install -y isc-dhcp-server
      tags: packages
      register: trixie_dhcp_install
      changed_when: "'0 upgraded, 0 newly installed' not in trixie_dhcp_install.stdout"
      when: ansible_distribution == "Debian" and ansible_distribution_release == "trixie"
      
    - name: Install ISC DHCP Server (non-Trixie)
      ansible.builtin.apt:
        name:
          - isc-dhcp-server
        state: present
        update_cache: yes
      tags: packages
      when: ansible_distribution != "Debian" or ansible_distribution_release != "trixie"
      
    - name: Backup existing DHCP configuration
      ansible.builtin.copy:
        src: /etc/dhcp/dhcpd.conf
        dest: /etc/dhcp/dhcpd.conf.backup.{{ ansible_date_time.epoch }}
        remote_src: yes
        mode: '0644'
      tags: backup
      ignore_errors: yes
      
    - name: Configure DHCP server
      ansible.builtin.copy:
        dest: /etc/dhcp/dhcpd.conf
        mode: '0644'
        content: |
          # DHCP Server Configuration for Home Router
          # Generated by Ansible
          
          # Global settings
          default-lease-time 600;
          max-lease-time 7200;
          authoritative;
          
          # DNS settings
          option domain-name "{{ dhcp_domain | default('home.local') }}";
          option domain-name-servers {{ dhcp_dns_servers | default('8.8.8.8, 8.8.4.4') }};
          
          # Main Network ({{ local_interface }})
          subnet {{ local_ip | regex_replace('\\.\\d+$', '.0') }} netmask {{ local_netmask }} {
              range {{ local_dhcp_range_start | default(local_ip | regex_replace('\\.\\d+$', '.50')) }} {{ local_dhcp_range_end | default(local_ip | regex_replace('\\.\\d+$', '.150')) }};
              option routers {{ local_ip }};
              option broadcast-address {{ local_ip | regex_replace('\\.\\d+$', '.255') }};
          }
          
          {% if vlan3_interface is defined and vlan3_ip is defined %}
          # VLAN 3 - Private Network ({{ vlan3_interface }})
          subnet {{ vlan3_ip | regex_replace('\\.\\d+$', '.0') }} netmask {{ vlan3_netmask }} {
              range {{ vlan3_dhcp_range_start | default(vlan3_ip | regex_replace('\\.\\d+$', '.50')) }} {{ vlan3_dhcp_range_end | default(vlan3_ip | regex_replace('\\.\\d+$', '.150')) }};
              option routers {{ vlan3_ip }};
              option broadcast-address {{ vlan3_ip | regex_replace('\\.\\d+$', '.255') }};
          }
          {% endif %}
          
          {% if vlan4_interface is defined and vlan4_ip is defined %}
          # VLAN 4 - Home Assistant Network ({{ vlan4_interface }})
          subnet {{ vlan4_ip | regex_replace('\\.\\d+$', '.0') }} netmask {{ vlan4_netmask }} {
              range {{ vlan4_dhcp_range_start | default(vlan4_ip | regex_replace('\\.\\d+$', '.50')) }} {{ vlan4_dhcp_range_end | default(vlan4_ip | regex_replace('\\.\\d+$', '.150')) }};
              option routers {{ vlan4_ip }};
              option broadcast-address {{ vlan4_ip | regex_replace('\\.\\d+$', '.255') }};
          }
          {% endif %}
          
          {% if vlan5_interface is defined and vlan5_ip is defined %}
          # VLAN 5 - Guest Network ({{ vlan5_interface }})
          subnet {{ vlan5_ip | regex_replace('\\.\\d+$', '.0') }} netmask {{ vlan5_netmask }} {
              range {{ vlan5_dhcp_range_start | default(vlan5_ip | regex_replace('\\.\\d+$', '.50')) }} {{ vlan5_dhcp_range_end | default(vlan5_ip | regex_replace('\\.\\d+$', '.150')) }};
              option routers {{ vlan5_ip }};
              option broadcast-address {{ vlan5_ip | regex_replace('\\.\\d+$', '.255') }};
          }
          {% endif %}
      tags: configure
      notify: restart dhcpd
      
    - name: Configure DHCP server to listen on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: '^INTERFACESv4='
        line: 'INTERFACESv4="{{ local_interface }}{% if vlan3_interface is defined %} {{ vlan3_interface }}{% endif %}{% if vlan4_interface is defined %} {{ vlan4_interface }}{% endif %}{% if vlan5_interface is defined %} {{ vlan5_interface }}{% endif %}"'
        create: yes
        mode: '0644'
      tags: configure
      notify: restart dhcpd
      
    - name: Ensure DHCP server is enabled and started
      ansible.builtin.systemd:
        name: isc-dhcp-server
        enabled: yes
        state: started
      tags: service
      
    - name: Display DHCP configuration
      ansible.builtin.command: cat /etc/dhcp/dhcpd.conf
      register: dhcp_config
      changed_when: false
      tags: validate
      
    - name: Show DHCP configuration
      ansible.builtin.debug:
        var: dhcp_config.stdout_lines
      tags: validate
      
    - name: Check DHCP server status
      ansible.builtin.command: systemctl status isc-dhcp-server
      register: dhcp_status
      changed_when: false
      ignore_errors: yes
      tags: validate
      
    - name: Show DHCP server status
      ansible.builtin.debug:
        var: dhcp_status.stdout_lines
      tags: validate
      
    - name: Display DHCP leases file location
      ansible.builtin.debug:
        msg: |
          DHCP server is configured!
          
          Lease file: /var/lib/dhcp/dhcpd.leases
          Config file: /etc/dhcp/dhcpd.conf
          
          View active leases: cat /var/lib/dhcp/dhcpd.leases
          View DHCP logs: journalctl -u isc-dhcp-server -f
          Restart DHCP: systemctl restart isc-dhcp-server
          
          DHCP Ranges:
          - Main Network ({{ local_ip | regex_replace('\\.\\d+$', '.0') }}/24): {{ local_dhcp_range_start | default(local_ip | regex_replace('\\.\\d+$', '.50')) }} - {{ local_dhcp_range_end | default(local_ip | regex_replace('\\.\\d+$', '.150')) }}
          {% if vlan3_ip is defined %}- VLAN 3 ({{ vlan3_ip | regex_replace('\\.\\d+$', '.0') }}/24): {{ vlan3_dhcp_range_start | default(vlan3_ip | regex_replace('\\.\\d+$', '.50')) }} - {{ vlan3_dhcp_range_end | default(vlan3_ip | regex_replace('\\.\\d+$', '.150')) }}{% endif %}
          {% if vlan4_ip is defined %}- VLAN 4 ({{ vlan4_ip | regex_replace('\\.\\d+$', '.0') }}/24): {{ vlan4_dhcp_range_start | default(vlan4_ip | regex_replace('\\.\\d+$', '.50')) }} - {{ vlan4_dhcp_range_end | default(vlan4_ip | regex_replace('\\.\\d+$', '.150')) }}{% endif %}
          {% if vlan5_ip is defined %}- VLAN 5 ({{ vlan5_ip | regex_replace('\\.\\d+$', '.0') }}/24): {{ vlan5_dhcp_range_start | default(vlan5_ip | regex_replace('\\.\\d+$', '.50')) }} - {{ vlan5_dhcp_range_end | default(vlan5_ip | regex_replace('\\.\\d+$', '.150')) }}{% endif %}
      tags: documentation
      
  handlers:
    - name: restart dhcpd
      ansible.builtin.systemd:
        name: isc-dhcp-server
        state: restarted

